function Y = revoarm_right_getY_cpp(q, qd, qdd)
% Auto-generated MATLAB regressor for revoarm_right (7-body C++ model)
% Generated by: scripts/gen_matlab_regressor.py
% DOF=7, bodies=7, kinematic_prefix=2

% ---- sin/cos ------------------------------------------------
  s1 = sin(q(1)); c1 = cos(q(1));
  s2 = sin(q(2)); c2 = cos(q(2));
  s3 = sin(q(3)); c3 = cos(q(3));
  s4 = sin(q(4)); c4 = cos(q(4));
  s5 = sin(q(5)); c5 = cos(q(5));
  s6 = sin(q(6)); c6 = cos(q(6));
  s7 = sin(q(7)); c7 = cos(q(7));

  % Rodriguez R_joint for body 2 (right_arm_link1), joint 0
  ax_b2 = [0 1 0];
  Rj_b2 = eye(3) + s1*skew3(ax_b2) + (1-c1)*(skew3(ax_b2)*skew3(ax_b2));
  % Rodriguez R_joint for body 3 (right_arm_link2), joint 1
  ax_b3 = [-1 0 0];
  Rj_b3 = eye(3) + s2*skew3(ax_b3) + (1-c2)*(skew3(ax_b3)*skew3(ax_b3));
  % Rodriguez R_joint for body 4 (right_arm_link3), joint 2
  ax_b4 = [0 0 1];
  Rj_b4 = eye(3) + s3*skew3(ax_b4) + (1-c3)*(skew3(ax_b4)*skew3(ax_b4));
  % Rodriguez R_joint for body 5 (right_arm_link4), joint 3
  ax_b5 = [0 -1 0];
  Rj_b5 = eye(3) + s4*skew3(ax_b5) + (1-c4)*(skew3(ax_b5)*skew3(ax_b5));
  % Rodriguez R_joint for body 6 (right_arm_link5), joint 4
  ax_b6 = [0 0 1];
  Rj_b6 = eye(3) + s5*skew3(ax_b6) + (1-c5)*(skew3(ax_b6)*skew3(ax_b6));
  % Rodriguez R_joint for body 7 (right_arm_link6), joint 5
  ax_b7 = [1 0 0];
  Rj_b7 = eye(3) + s6*skew3(ax_b7) + (1-c6)*(skew3(ax_b7)*skew3(ax_b7));
  % Rodriguez R_joint for body 8 (right_arm_link7), joint 6
  ax_b8 = [0 -1 0];
  Rj_b8 = eye(3) + s7*skew3(ax_b8) + (1-c7)*(skew3(ax_b8)*skew3(ax_b8));

% ---- FK transforms ------------------------------------------
  Rc_b0 = [1 0 0; 0 1 0; 0 0 1];
  pc_b0 = [0 0 0]';
  Rc_b1 = [1 -0 0; 0 0.984808260963539 0.173645296907205; -0 -0.173645296907205 0.984808260963539];
  pc_b1 = [0.0055 -0.10424 -0.038037]';
  Rc_b2 = [1 0 0; 0 1 0; 0 0 1];
  pc_b2 = [0 0 0]';
  Rc_b3 = [1 0 0; 0 0.984808260963539 -0.173645296907205; 0 0.173645296907205 0.984808260963539];
  pc_b3 = [0 -0.06 0]';
  Rc_b4 = [1 0 0; 0 1 0; 0 0 1];
  pc_b4 = [0 0 -0.099]';
  Rc_b5 = [1 0 0; 0 1 0; 0 0 1];
  pc_b5 = [0 0 -0.121]';
  Rc_b6 = [1 0 0; 0 1 0; 0 0 1];
  pc_b6 = [0 0 -0.0635]';
  Rc_b7 = [1 0 0; 0 1 0; 0 0 1];
  pc_b7 = [0 0 -0.1525]';
  Rc_b8 = [1 0 0; 0 0.999998117424511 -0.00194039878235053; 0 0.00194039878235053 0.999998117424511];
  pc_b8 = [0 0 0]';

  % Accumulate transforms
  R{1} = Rc_b0; p{1} = pc_b0;
  R{2} = R{1} * Rc_b1;
  R{3} = R{2} * Rc_b2 * Rj_b2;  % body 2: right_arm_link1
  R{4} = R{3} * Rc_b3 * Rj_b3;  % body 3: right_arm_link2
  R{5} = R{4} * Rc_b4 * Rj_b4;  % body 4: right_arm_link3
  R{6} = R{5} * Rc_b5 * Rj_b5;  % body 5: right_arm_link4
  R{7} = R{6} * Rc_b6 * Rj_b6;  % body 6: right_arm_link5
  R{8} = R{7} * Rc_b7 * Rj_b7;  % body 7: right_arm_link6
  R{9} = R{8} * Rc_b8 * Rj_b8;  % body 8: right_arm_link7
  p{2} = p{1} + R{1} * pc_b1;
  p{3} = p{2} + R{2} * pc_b2;
  p{4} = p{3} + R{3} * pc_b3;
  p{5} = p{4} + R{4} * pc_b4;
  p{6} = p{5} + R{5} * pc_b5;
  p{7} = p{6} + R{6} * pc_b6;
  p{8} = p{7} + R{7} * pc_b7;
  p{9} = p{8} + R{8} * pc_b8;

% ---- Jacobian & regressor blocks ----------------------------
  Y = zeros(7, 70);
  g = [0; 0; -9.81];

  % --- body 0 (right_arm_link1) ---
  Rt = R{3}';
  p_body = p{3};
  Jv = zeros(3,7); Jw = zeros(3,7);
  r = p_body - p{3};
  z = R{3} * [0;1;0];
  Jv(:,1) = Rt * cross(z, r);
  Jw(:,1) = Rt * z;
  a_w = Jv * qdd;  % simplified (no Jv_dot contribution for small qd)
  om_w = Jw * qd;
  al_w = Jw * qdd;
  a_loc = Rt * a_w; om_loc = Rt * om_w; al_loc = Rt * al_w;
  g_loc = Rt * g;
  b_loc = a_loc - g_loc;
  Jv_loc = Rt * Jv; Jw_loc = Rt * Jw;

  ox=om_loc(1); oy=om_loc(2); oz=om_loc(3);
  ax=al_loc(1); ay=al_loc(2); az=al_loc(3);
  K = skew3(al_loc) + skew3(om_loc)*skew3(om_loc);

  off = 0;
  Y(:,off+1) = Jv_loc' * b_loc;  % m
  e1 = zeros(3,1); e1(1) = 1;
  Y(:,off+2) = Jv_loc' * K(:,1) + Jw_loc' * cross(e1, b_loc);  % mx
  e2 = zeros(3,1); e2(2) = 1;
  Y(:,off+3) = Jv_loc' * K(:,2) + Jw_loc' * cross(e2, b_loc);  % my
  e3 = zeros(3,1); e3(3) = 1;
  Y(:,off+4) = Jv_loc' * K(:,3) + Jw_loc' * cross(e3, b_loc);  % mz
  Y(:,off+5) = Jw_loc' * [ax; ox*oz; -ox*oy];  % Ixx
  Y(:,off+6) = Jw_loc' * [ay-ox*oz; ax+oy*oz; ox*ox-oy*oy];  % Ixy
  Y(:,off+7) = Jw_loc' * [az+ox*oy; oz*oz-ox*ox; ax-oy*oz];  % Ixz
  Y(:,off+8) = Jw_loc' * [-oy*oz; ay; ox*oy];  % Iyy
  Y(:,off+9) = Jw_loc' * [oy*oy-oz*oz; az-ox*oy; ay+ox*oz];  % Iyz
  Y(:,off+10) = Jw_loc' * [oy*oz; -ox*oz; az];  % Izz

  % --- body 1 (right_arm_link2) ---
  Rt = R{4}';
  p_body = p{4};
  Jv = zeros(3,7); Jw = zeros(3,7);
  r = p_body - p{3};
  z = R{3} * [0;1;0];
  Jv(:,1) = Rt * cross(z, r);
  Jw(:,1) = Rt * z;
  r = p_body - p{4};
  z = R{4} * [-1;0;0];
  Jv(:,2) = Rt * cross(z, r);
  Jw(:,2) = Rt * z;
  a_w = Jv * qdd;  % simplified (no Jv_dot contribution for small qd)
  om_w = Jw * qd;
  al_w = Jw * qdd;
  a_loc = Rt * a_w; om_loc = Rt * om_w; al_loc = Rt * al_w;
  g_loc = Rt * g;
  b_loc = a_loc - g_loc;
  Jv_loc = Rt * Jv; Jw_loc = Rt * Jw;

  ox=om_loc(1); oy=om_loc(2); oz=om_loc(3);
  ax=al_loc(1); ay=al_loc(2); az=al_loc(3);
  K = skew3(al_loc) + skew3(om_loc)*skew3(om_loc);

  off = 10;
  Y(:,off+1) = Jv_loc' * b_loc;  % m
  e1 = zeros(3,1); e1(1) = 1;
  Y(:,off+2) = Jv_loc' * K(:,1) + Jw_loc' * cross(e1, b_loc);  % mx
  e2 = zeros(3,1); e2(2) = 1;
  Y(:,off+3) = Jv_loc' * K(:,2) + Jw_loc' * cross(e2, b_loc);  % my
  e3 = zeros(3,1); e3(3) = 1;
  Y(:,off+4) = Jv_loc' * K(:,3) + Jw_loc' * cross(e3, b_loc);  % mz
  Y(:,off+5) = Jw_loc' * [ax; ox*oz; -ox*oy];  % Ixx
  Y(:,off+6) = Jw_loc' * [ay-ox*oz; ax+oy*oz; ox*ox-oy*oy];  % Ixy
  Y(:,off+7) = Jw_loc' * [az+ox*oy; oz*oz-ox*ox; ax-oy*oz];  % Ixz
  Y(:,off+8) = Jw_loc' * [-oy*oz; ay; ox*oy];  % Iyy
  Y(:,off+9) = Jw_loc' * [oy*oy-oz*oz; az-ox*oy; ay+ox*oz];  % Iyz
  Y(:,off+10) = Jw_loc' * [oy*oz; -ox*oz; az];  % Izz

  % --- body 2 (right_arm_link3) ---
  Rt = R{5}';
  p_body = p{5};
  Jv = zeros(3,7); Jw = zeros(3,7);
  r = p_body - p{3};
  z = R{3} * [0;1;0];
  Jv(:,1) = Rt * cross(z, r);
  Jw(:,1) = Rt * z;
  r = p_body - p{4};
  z = R{4} * [-1;0;0];
  Jv(:,2) = Rt * cross(z, r);
  Jw(:,2) = Rt * z;
  r = p_body - p{5};
  z = R{5} * [0;0;1];
  Jv(:,3) = Rt * cross(z, r);
  Jw(:,3) = Rt * z;
  a_w = Jv * qdd;  % simplified (no Jv_dot contribution for small qd)
  om_w = Jw * qd;
  al_w = Jw * qdd;
  a_loc = Rt * a_w; om_loc = Rt * om_w; al_loc = Rt * al_w;
  g_loc = Rt * g;
  b_loc = a_loc - g_loc;
  Jv_loc = Rt * Jv; Jw_loc = Rt * Jw;

  ox=om_loc(1); oy=om_loc(2); oz=om_loc(3);
  ax=al_loc(1); ay=al_loc(2); az=al_loc(3);
  K = skew3(al_loc) + skew3(om_loc)*skew3(om_loc);

  off = 20;
  Y(:,off+1) = Jv_loc' * b_loc;  % m
  e1 = zeros(3,1); e1(1) = 1;
  Y(:,off+2) = Jv_loc' * K(:,1) + Jw_loc' * cross(e1, b_loc);  % mx
  e2 = zeros(3,1); e2(2) = 1;
  Y(:,off+3) = Jv_loc' * K(:,2) + Jw_loc' * cross(e2, b_loc);  % my
  e3 = zeros(3,1); e3(3) = 1;
  Y(:,off+4) = Jv_loc' * K(:,3) + Jw_loc' * cross(e3, b_loc);  % mz
  Y(:,off+5) = Jw_loc' * [ax; ox*oz; -ox*oy];  % Ixx
  Y(:,off+6) = Jw_loc' * [ay-ox*oz; ax+oy*oz; ox*ox-oy*oy];  % Ixy
  Y(:,off+7) = Jw_loc' * [az+ox*oy; oz*oz-ox*ox; ax-oy*oz];  % Ixz
  Y(:,off+8) = Jw_loc' * [-oy*oz; ay; ox*oy];  % Iyy
  Y(:,off+9) = Jw_loc' * [oy*oy-oz*oz; az-ox*oy; ay+ox*oz];  % Iyz
  Y(:,off+10) = Jw_loc' * [oy*oz; -ox*oz; az];  % Izz

  % --- body 3 (right_arm_link4) ---
  Rt = R{6}';
  p_body = p{6};
  Jv = zeros(3,7); Jw = zeros(3,7);
  r = p_body - p{3};
  z = R{3} * [0;1;0];
  Jv(:,1) = Rt * cross(z, r);
  Jw(:,1) = Rt * z;
  r = p_body - p{4};
  z = R{4} * [-1;0;0];
  Jv(:,2) = Rt * cross(z, r);
  Jw(:,2) = Rt * z;
  r = p_body - p{5};
  z = R{5} * [0;0;1];
  Jv(:,3) = Rt * cross(z, r);
  Jw(:,3) = Rt * z;
  r = p_body - p{6};
  z = R{6} * [0;-1;0];
  Jv(:,4) = Rt * cross(z, r);
  Jw(:,4) = Rt * z;
  a_w = Jv * qdd;  % simplified (no Jv_dot contribution for small qd)
  om_w = Jw * qd;
  al_w = Jw * qdd;
  a_loc = Rt * a_w; om_loc = Rt * om_w; al_loc = Rt * al_w;
  g_loc = Rt * g;
  b_loc = a_loc - g_loc;
  Jv_loc = Rt * Jv; Jw_loc = Rt * Jw;

  ox=om_loc(1); oy=om_loc(2); oz=om_loc(3);
  ax=al_loc(1); ay=al_loc(2); az=al_loc(3);
  K = skew3(al_loc) + skew3(om_loc)*skew3(om_loc);

  off = 30;
  Y(:,off+1) = Jv_loc' * b_loc;  % m
  e1 = zeros(3,1); e1(1) = 1;
  Y(:,off+2) = Jv_loc' * K(:,1) + Jw_loc' * cross(e1, b_loc);  % mx
  e2 = zeros(3,1); e2(2) = 1;
  Y(:,off+3) = Jv_loc' * K(:,2) + Jw_loc' * cross(e2, b_loc);  % my
  e3 = zeros(3,1); e3(3) = 1;
  Y(:,off+4) = Jv_loc' * K(:,3) + Jw_loc' * cross(e3, b_loc);  % mz
  Y(:,off+5) = Jw_loc' * [ax; ox*oz; -ox*oy];  % Ixx
  Y(:,off+6) = Jw_loc' * [ay-ox*oz; ax+oy*oz; ox*ox-oy*oy];  % Ixy
  Y(:,off+7) = Jw_loc' * [az+ox*oy; oz*oz-ox*ox; ax-oy*oz];  % Ixz
  Y(:,off+8) = Jw_loc' * [-oy*oz; ay; ox*oy];  % Iyy
  Y(:,off+9) = Jw_loc' * [oy*oy-oz*oz; az-ox*oy; ay+ox*oz];  % Iyz
  Y(:,off+10) = Jw_loc' * [oy*oz; -ox*oz; az];  % Izz

  % --- body 4 (right_arm_link5) ---
  Rt = R{7}';
  p_body = p{7};
  Jv = zeros(3,7); Jw = zeros(3,7);
  r = p_body - p{3};
  z = R{3} * [0;1;0];
  Jv(:,1) = Rt * cross(z, r);
  Jw(:,1) = Rt * z;
  r = p_body - p{4};
  z = R{4} * [-1;0;0];
  Jv(:,2) = Rt * cross(z, r);
  Jw(:,2) = Rt * z;
  r = p_body - p{5};
  z = R{5} * [0;0;1];
  Jv(:,3) = Rt * cross(z, r);
  Jw(:,3) = Rt * z;
  r = p_body - p{6};
  z = R{6} * [0;-1;0];
  Jv(:,4) = Rt * cross(z, r);
  Jw(:,4) = Rt * z;
  r = p_body - p{7};
  z = R{7} * [0;0;1];
  Jv(:,5) = Rt * cross(z, r);
  Jw(:,5) = Rt * z;
  a_w = Jv * qdd;  % simplified (no Jv_dot contribution for small qd)
  om_w = Jw * qd;
  al_w = Jw * qdd;
  a_loc = Rt * a_w; om_loc = Rt * om_w; al_loc = Rt * al_w;
  g_loc = Rt * g;
  b_loc = a_loc - g_loc;
  Jv_loc = Rt * Jv; Jw_loc = Rt * Jw;

  ox=om_loc(1); oy=om_loc(2); oz=om_loc(3);
  ax=al_loc(1); ay=al_loc(2); az=al_loc(3);
  K = skew3(al_loc) + skew3(om_loc)*skew3(om_loc);

  off = 40;
  Y(:,off+1) = Jv_loc' * b_loc;  % m
  e1 = zeros(3,1); e1(1) = 1;
  Y(:,off+2) = Jv_loc' * K(:,1) + Jw_loc' * cross(e1, b_loc);  % mx
  e2 = zeros(3,1); e2(2) = 1;
  Y(:,off+3) = Jv_loc' * K(:,2) + Jw_loc' * cross(e2, b_loc);  % my
  e3 = zeros(3,1); e3(3) = 1;
  Y(:,off+4) = Jv_loc' * K(:,3) + Jw_loc' * cross(e3, b_loc);  % mz
  Y(:,off+5) = Jw_loc' * [ax; ox*oz; -ox*oy];  % Ixx
  Y(:,off+6) = Jw_loc' * [ay-ox*oz; ax+oy*oz; ox*ox-oy*oy];  % Ixy
  Y(:,off+7) = Jw_loc' * [az+ox*oy; oz*oz-ox*ox; ax-oy*oz];  % Ixz
  Y(:,off+8) = Jw_loc' * [-oy*oz; ay; ox*oy];  % Iyy
  Y(:,off+9) = Jw_loc' * [oy*oy-oz*oz; az-ox*oy; ay+ox*oz];  % Iyz
  Y(:,off+10) = Jw_loc' * [oy*oz; -ox*oz; az];  % Izz

  % --- body 5 (right_arm_link6) ---
  Rt = R{8}';
  p_body = p{8};
  Jv = zeros(3,7); Jw = zeros(3,7);
  r = p_body - p{3};
  z = R{3} * [0;1;0];
  Jv(:,1) = Rt * cross(z, r);
  Jw(:,1) = Rt * z;
  r = p_body - p{4};
  z = R{4} * [-1;0;0];
  Jv(:,2) = Rt * cross(z, r);
  Jw(:,2) = Rt * z;
  r = p_body - p{5};
  z = R{5} * [0;0;1];
  Jv(:,3) = Rt * cross(z, r);
  Jw(:,3) = Rt * z;
  r = p_body - p{6};
  z = R{6} * [0;-1;0];
  Jv(:,4) = Rt * cross(z, r);
  Jw(:,4) = Rt * z;
  r = p_body - p{7};
  z = R{7} * [0;0;1];
  Jv(:,5) = Rt * cross(z, r);
  Jw(:,5) = Rt * z;
  r = p_body - p{8};
  z = R{8} * [1;0;0];
  Jv(:,6) = Rt * cross(z, r);
  Jw(:,6) = Rt * z;
  a_w = Jv * qdd;  % simplified (no Jv_dot contribution for small qd)
  om_w = Jw * qd;
  al_w = Jw * qdd;
  a_loc = Rt * a_w; om_loc = Rt * om_w; al_loc = Rt * al_w;
  g_loc = Rt * g;
  b_loc = a_loc - g_loc;
  Jv_loc = Rt * Jv; Jw_loc = Rt * Jw;

  ox=om_loc(1); oy=om_loc(2); oz=om_loc(3);
  ax=al_loc(1); ay=al_loc(2); az=al_loc(3);
  K = skew3(al_loc) + skew3(om_loc)*skew3(om_loc);

  off = 50;
  Y(:,off+1) = Jv_loc' * b_loc;  % m
  e1 = zeros(3,1); e1(1) = 1;
  Y(:,off+2) = Jv_loc' * K(:,1) + Jw_loc' * cross(e1, b_loc);  % mx
  e2 = zeros(3,1); e2(2) = 1;
  Y(:,off+3) = Jv_loc' * K(:,2) + Jw_loc' * cross(e2, b_loc);  % my
  e3 = zeros(3,1); e3(3) = 1;
  Y(:,off+4) = Jv_loc' * K(:,3) + Jw_loc' * cross(e3, b_loc);  % mz
  Y(:,off+5) = Jw_loc' * [ax; ox*oz; -ox*oy];  % Ixx
  Y(:,off+6) = Jw_loc' * [ay-ox*oz; ax+oy*oz; ox*ox-oy*oy];  % Ixy
  Y(:,off+7) = Jw_loc' * [az+ox*oy; oz*oz-ox*ox; ax-oy*oz];  % Ixz
  Y(:,off+8) = Jw_loc' * [-oy*oz; ay; ox*oy];  % Iyy
  Y(:,off+9) = Jw_loc' * [oy*oy-oz*oz; az-ox*oy; ay+ox*oz];  % Iyz
  Y(:,off+10) = Jw_loc' * [oy*oz; -ox*oz; az];  % Izz

  % --- body 6 (right_arm_link7) ---
  Rt = R{9}';
  p_body = p{9};
  Jv = zeros(3,7); Jw = zeros(3,7);
  r = p_body - p{3};
  z = R{3} * [0;1;0];
  Jv(:,1) = Rt * cross(z, r);
  Jw(:,1) = Rt * z;
  r = p_body - p{4};
  z = R{4} * [-1;0;0];
  Jv(:,2) = Rt * cross(z, r);
  Jw(:,2) = Rt * z;
  r = p_body - p{5};
  z = R{5} * [0;0;1];
  Jv(:,3) = Rt * cross(z, r);
  Jw(:,3) = Rt * z;
  r = p_body - p{6};
  z = R{6} * [0;-1;0];
  Jv(:,4) = Rt * cross(z, r);
  Jw(:,4) = Rt * z;
  r = p_body - p{7};
  z = R{7} * [0;0;1];
  Jv(:,5) = Rt * cross(z, r);
  Jw(:,5) = Rt * z;
  r = p_body - p{8};
  z = R{8} * [1;0;0];
  Jv(:,6) = Rt * cross(z, r);
  Jw(:,6) = Rt * z;
  r = p_body - p{9};
  z = R{9} * [0;-1;0];
  Jv(:,7) = Rt * cross(z, r);
  Jw(:,7) = Rt * z;
  a_w = Jv * qdd;  % simplified (no Jv_dot contribution for small qd)
  om_w = Jw * qd;
  al_w = Jw * qdd;
  a_loc = Rt * a_w; om_loc = Rt * om_w; al_loc = Rt * al_w;
  g_loc = Rt * g;
  b_loc = a_loc - g_loc;
  Jv_loc = Rt * Jv; Jw_loc = Rt * Jw;

  ox=om_loc(1); oy=om_loc(2); oz=om_loc(3);
  ax=al_loc(1); ay=al_loc(2); az=al_loc(3);
  K = skew3(al_loc) + skew3(om_loc)*skew3(om_loc);

  off = 60;
  Y(:,off+1) = Jv_loc' * b_loc;  % m
  e1 = zeros(3,1); e1(1) = 1;
  Y(:,off+2) = Jv_loc' * K(:,1) + Jw_loc' * cross(e1, b_loc);  % mx
  e2 = zeros(3,1); e2(2) = 1;
  Y(:,off+3) = Jv_loc' * K(:,2) + Jw_loc' * cross(e2, b_loc);  % my
  e3 = zeros(3,1); e3(3) = 1;
  Y(:,off+4) = Jv_loc' * K(:,3) + Jw_loc' * cross(e3, b_loc);  % mz
  Y(:,off+5) = Jw_loc' * [ax; ox*oz; -ox*oy];  % Ixx
  Y(:,off+6) = Jw_loc' * [ay-ox*oz; ax+oy*oz; ox*ox-oy*oy];  % Ixy
  Y(:,off+7) = Jw_loc' * [az+ox*oy; oz*oz-ox*ox; ax-oy*oz];  % Ixz
  Y(:,off+8) = Jw_loc' * [-oy*oz; ay; ox*oy];  % Iyy
  Y(:,off+9) = Jw_loc' * [oy*oy-oz*oz; az-ox*oy; ay+ox*oz];  % Iyz
  Y(:,off+10) = Jw_loc' * [oy*oz; -ox*oz; az];  % Izz

end

function S = skew3(v)
  S = [0 -v(3) v(2); v(3) 0 -v(1); -v(2) v(1) 0];
end