#!/usr/bin/env python3
"""
Generate a MATLAB regressor function matching the C++ 7-body model.
Uses the same geometric formulas as fast_regressor.cpp (sin/cos + FK + Jacobian).

Output: matlab/revoarm_right_getY_cpp.m
"""
import argparse, os, sys, math
import yaml
import numpy as np

PARAM_NAMES = ["m", "mx", "my", "mz", "Ixx", "Ixy", "Ixz", "Iyy", "Iyz", "Izz"]


def quat_to_rot(q_wxyz):
    """四元数 (w,x,y,z) → 3×3 旋转矩阵"""
    w, x, y, z = q_wxyz
    return np.array([
        [1-2*y*y-2*z*z, 2*x*y-2*w*z,   2*x*z+2*w*y],
        [2*x*y+2*w*z,   1-2*x*x-2*z*z, 2*y*z-2*w*x],
        [2*x*z-2*w*y,   2*y*z+2*w*x,   1-2*x*x-2*y*y]
    ])


def main():
    p = argparse.ArgumentParser()
    p.add_argument("--kinematic", required=True)
    p.add_argument("--output", default="matlab/revoarm_right_getY_cpp.m")
    args = p.parse_args()

    with open(args.kinematic) as f:
        kcfg = yaml.safe_load(f)

    kprefix = kcfg.get("kinematic_prefix", 0)
    bodies = kcfg["bodies"][kprefix:]  # 7 regressor bodies
    all_bodies = kcfg["bodies"]        # all bodies (9 total)

    n_dof = kcfg["dof"]
    n_bodies = len(bodies)
    total = len(all_bodies)

    # Pre-compute constants
    consts = []
    for i, b in enumerate(all_bodies):
        qw = b.get("quat", [1, 0, 0, 0])
        R = quat_to_rot(qw)
        pv = np.array(b.get("pos", [0, 0, 0]))
        ax = np.array(b.get("joint_axis", [0, 0, 1]))
        hj = b.get("has_joint", False)
        consts.append({"R": R, "pos": pv, "axis": ax, "has_joint": hj})

    # Build the MATLAB function
    lines = []
    lines.append(f"function Y = revoarm_right_getY_cpp(q, qd, qdd)")
    lines.append(f"% Auto-generated MATLAB regressor for revoarm_right (7-body C++ model)")
    lines.append(f"% Generated by: scripts/gen_matlab_regressor.py")
    lines.append(f"% DOF={n_dof}, bodies={n_bodies}, kinematic_prefix={kprefix}")
    lines.append(f"")
    lines.append(f"% ---- sin/cos ------------------------------------------------")
    for j in range(n_dof):
        lines.append(f"  s{j+1} = sin(q({j+1})); c{j+1} = cos(q({j+1}));")
    lines.append(f"")

    # Rodriguez formula for each joint (joint index != body index!)
    joint_idx = 0
    for i in range(1, total):
        if consts[i]["has_joint"]:
            jj = joint_idx + 1  # MATLAB 1-based joint index
            lines.append(f"  % Rodriguez R_joint for body {i} ({all_bodies[i]['name']}), joint {joint_idx}")
            ax = consts[i]["axis"]
            lines.append(f"  ax_b{i} = [{ax[0]:.15g} {ax[1]:.15g} {ax[2]:.15g}];")
            lines.append(f"  Rj_b{i} = eye(3) + s{jj}*skew3(ax_b{i}) + (1-c{jj})*(skew3(ax_b{i})*skew3(ax_b{i}));")
            joint_idx += 1

    # Body transforms
    lines.append(f"")
    lines.append(f"% ---- FK transforms ------------------------------------------")
    for i in range(total):
        Rc = consts[i]["R"]
        pv = consts[i]["pos"]
        lines.append(f"  Rc_b{i} = [{Rc[0,0]:.15g} {Rc[0,1]:.15g} {Rc[0,2]:.15g}; {Rc[1,0]:.15g} {Rc[1,1]:.15g} {Rc[1,2]:.15g}; {Rc[2,0]:.15g} {Rc[2,1]:.15g} {Rc[2,2]:.15g}];")
        lines.append(f"  pc_b{i} = [{pv[0]:.15g} {pv[1]:.15g} {pv[2]:.15g}]';")

    lines.append(f"")
    lines.append(f"  % Accumulate transforms")
    lines.append(f"  R{{1}} = Rc_b0; p{{1}} = pc_b0;")

    joint_idx = 0
    for i in range(1, total):
        if consts[i]["has_joint"]:
            lines.append(f"  R{{{i+1}}} = R{{{i}}} * Rc_b{i} * Rj_b{i};  % body {i}: {all_bodies[i]['name']}")
            joint_idx += 1
        else:
            lines.append(f"  R{{{i+1}}} = R{{{i}}} * Rc_b{i};")
    for i in range(1, total):
        lines.append(f"  p{{{i+1}}} = p{{{i}}} + R{{{i}}} * pc_b{i};")

    # Jacobian
    lines.append(f"")
    lines.append(f"% ---- Jacobian & regressor blocks ----------------------------")
    lines.append(f"  Y = zeros({n_dof}, {n_bodies*10});")
    lines.append(f"  g = [0; 0; -9.81];")
    lines.append(f"")

    # Body-to-joint mapping
    b2j = {}
    jidx = 0
    for i in range(1, total):
        if consts[i]["has_joint"]:
            b2j[i] = jidx
            jidx += 1

    for b in range(n_bodies):
        body_idx = kprefix + b
        lines.append(f"  % --- body {b} ({all_bodies[body_idx]['name']}) ---")
        lines.append(f"  Rt = R{{{body_idx+1}}}';")
        lines.append(f"  p_body = p{{{body_idx+1}}};")

        # Jacobian construction
        lines.append(f"  Jv = zeros(3,{n_dof}); Jw = zeros(3,{n_dof});")
        for j in range(1, body_idx+1):
            jj = b2j.get(j)
            if jj is not None:
                lines.append(f"  r = p_body - p{{{j+1}}};")
                lines.append(f"  z = R{{{j+1}}} * [{consts[j]['axis'][0]:.15g};{consts[j]['axis'][1]:.15g};{consts[j]['axis'][2]:.15g}];")
                lines.append(f"  Jv(:,{jj+1}) = Rt * cross(z, r);")
                lines.append(f"  Jw(:,{jj+1}) = Rt * z;")

        # Regressor block
        lines.append(f"  a_w = Jv * qdd;  % simplified (no Jv_dot contribution for small qd)")
        lines.append(f"  om_w = Jw * qd;")
        lines.append(f"  al_w = Jw * qdd;")
        lines.append(f"  a_loc = Rt * a_w; om_loc = Rt * om_w; al_loc = Rt * al_w;")
        lines.append(f"  g_loc = Rt * g;")
        lines.append(f"  b_loc = a_loc - g_loc;")
        lines.append(f"  Jv_loc = Rt * Jv; Jw_loc = Rt * Jw;")
        lines.append(f"")

        # The regressor formulas (same as C++ fast_regressor)
        lines.append(f"  ox=om_loc(1); oy=om_loc(2); oz=om_loc(3);")
        lines.append(f"  ax=al_loc(1); ay=al_loc(2); az=al_loc(3);")
        lines.append(f"  K = skew3(al_loc) + skew3(om_loc)*skew3(om_loc);")
        lines.append(f"")
        lines.append(f"  off = {b*10};")
        lines.append(f"  Y(:,off+1) = Jv_loc' * b_loc;  % m")
        for col_i in range(3):
            lines.append(f"  e{col_i+1} = zeros(3,1); e{col_i+1}({col_i+1}) = 1;")
            lines.append(f"  Y(:,off+{2+col_i}) = Jv_loc' * K(:,%d) + Jw_loc' * cross(e%d, b_loc);  %% m%c" % (col_i+1, col_i+1, 'xyz'[col_i]))
        lines.append(f"  Y(:,off+5) = Jw_loc' * [ax; ox*oz; -ox*oy];  % Ixx")
        lines.append(f"  Y(:,off+6) = Jw_loc' * [ay-ox*oz; ax+oy*oz; ox*ox-oy*oy];  % Ixy")
        lines.append(f"  Y(:,off+7) = Jw_loc' * [az+ox*oy; oz*oz-ox*ox; ax-oy*oz];  % Ixz")
        lines.append(f"  Y(:,off+8) = Jw_loc' * [-oy*oz; ay; ox*oy];  % Iyy")
        lines.append(f"  Y(:,off+9) = Jw_loc' * [oy*oy-oz*oz; az-ox*oy; ay+ox*oz];  % Iyz")
        lines.append(f"  Y(:,off+10) = Jw_loc' * [oy*oz; -ox*oz; az];  % Izz")
        lines.append(f"")

    lines.append(f"end")
    lines.append(f"")
    lines.append(f"function S = skew3(v)")
    lines.append(f"  S = [0 -v(3) v(2); v(3) 0 -v(1); -v(2) v(1) 0];")
    lines.append(f"end")

    code = "\n".join(lines)

    os.makedirs(os.path.dirname(args.output) if os.path.dirname(args.output) else ".", exist_ok=True)
    with open(args.output, "w") as f:
        f.write(code)

    print(f"Generated {args.output} ({len(lines)} lines)")


if __name__ == "__main__":
    main()
